language: node_js
script:
  - npm run build    
before_deploy:
  - head -n 1 .gitignore > .gitignore.tmp
  - mv .gitignore.tmp .gitignore
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
